# Generated by Django 3.1 on 2020-12-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseinstance',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
