# Generated by Django 3.1 on 2020-12-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='enroll',
        ),
    ]
