# Generated by Django 3.1 on 2020-12-24 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courseinstance_sub_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffworker',
            name='profile',
        ),
    ]
