# Generated by Django 3.1 on 2020-12-31 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201231_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalassignment',
            old_name='answer_files',
            new_name='answer_file',
        ),
    ]
