# Generated by Django 3.1 on 2020-12-24 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_staffworker_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffworker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='staffworker_ptr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='supervised_courses',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='StaffWorker',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
