# Generated by Django 3.1 on 2020-12-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20201224_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='enroll',
            name='is_course_finished',
            field=models.BooleanField(default=False),
        ),
    ]
