# Generated by Django 3.1 on 2020-12-31 18:57

import courses.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201231_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalassignment',
            name='grade',
            field=models.SmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='personalassignment',
            name='answer_file',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.student_answers_directory_path),
        ),
    ]
