# Generated by Django 3.1 on 2020-12-29 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='student',
        ),
    ]
