# Generated by Django 3.1 on 2021-01-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210101_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalassignment',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
