# Generated by Django 3.1 on 2020-12-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='supervised_courses',
            field=models.ManyToManyField(related_name='teachers', to='courses.CourseInstance'),
        ),
        migrations.AddField(
            model_name='manager',
            name='supervised_course_instances',
            field=models.ManyToManyField(related_name='managers', to='courses.CourseInstance'),
        ),
        migrations.AddField(
            model_name='manager',
            name='supervised_courses',
            field=models.ManyToManyField(related_name='managers', to='courses.Course'),
        ),
    ]
