# Generated by Django 3.1 on 2020-12-24 10:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201224_1322'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('staffworker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.staffworker')),
                ('supervised_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='courses.courseinstance')),
            ],
            bases=('accounts.staffworker',),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('staffworker_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts.staffworker')),
                ('supervised_course_instances', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='courses.courseinstance')),
                ('supervised_courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='courses.course')),
            ],
            bases=('accounts.staffworker',),
        ),
    ]
