# Generated by Django 3.1 on 2020-12-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20201224_1322'),
        ('accounts', '0002_manager_staffworker_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='supervised_course_instances',
        ),
        migrations.AddField(
            model_name='manager',
            name='supervised_course_instances',
            field=models.ManyToManyField(related_name='managers', to='courses.CourseInstance'),
        ),
        migrations.RemoveField(
            model_name='manager',
            name='supervised_courses',
        ),
        migrations.AddField(
            model_name='manager',
            name='supervised_courses',
            field=models.ManyToManyField(related_name='managers', to='courses.Course'),
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='supervised_courses',
        ),
        migrations.AddField(
            model_name='teacher',
            name='supervised_courses',
            field=models.ManyToManyField(related_name='teachers', to='courses.CourseInstance'),
        ),
    ]
